name: stegcrypt_plus
description: StegCrypt+ Flutter frontend
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  socket_io_client: ^2.0.0
  shared_preferences: ^2.1.1
  provider: ^6.0.5
  cryptography: ^2.0.0
  pointycastle: ^3.7.0
  image: ^4.6.0
  flutter_secure_storage: ^8.0.0
  file_picker: ^5.3.2
  http_parser: ^4.0.0
  path_provider: ^2.0.14
  mime: ^1.0.2
  path: ^1.8.3
  flutter_svg: ^1.1.6
  animations: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
